// Code generated by hookah, DO NOT EDIT.
package test

type HookedPerson struct {
	*hookah.Hookah[Person]
}

func (h HookedPerson) Age() int {
	returnValues := h.RunMethodWithReturnHooks("Age")
	returnValue0 := returnValues[0].Interface().(int)
	return returnValue0
}
func (h HookedPerson) Name() string {
	returnValues := h.RunMethodWithReturnHooks("Name")
	returnValue0 := returnValues[0].Interface().(string)
	return returnValue0
}
func (h HookedPerson) SetName(name string) error {
	returnValues := h.RunMethodWithReturnHooks("SetName", name)
	var returnValue0 error
	returnValue0Any := returnValues[0].Interface()
	if returnValue0Any != nil {
		returnValue0 = returnValue0Any.(error)
	}
	return returnValue0
}
